### ISSUE TITLE
Issue with Master::Base::NIO NameError

### ISSUE THREAD

**Issue by schlende** [ondra-m/ruby-spark#5]
Really cool project. I've almost got things working but running into this error.

master.rb:39:in `run': uninitialized constant Master::Base::NIO (NameError)
	from master.rb:144:in `<main>'
15/05/15 22:49:23 ERROR executor.Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.net.SocketTimeoutException: Accept timed out
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
	at java.net.ServerSocket.implAccept(ServerSocket.java:530)
	at java.net.ServerSocket.accept(ServerSocket.java:498)
	at org.apache.spark.api.ruby.RubyWorker$.createWorker(RubyWorker.scala:70)
	at org.apache.spark.api.ruby.RubyWorker$.create(RubyWorker.scala:51)
	at org.apache.spark.api.ruby.RubyRDD.compute(RubyRDD.scala:50)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
15/05/15 22:49:23 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.net.SocketTimeoutException: Accept timed out
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
	at java.net.ServerSocket.implAccept(ServerSocket.java:530)
	at java.net.ServerSocket.accept(ServerSocket.java:498)
	at org.apache.spark.api.ruby.RubyWorker$.createWorker(RubyWorker.scala:70)
	at org.apache.spark.api.ruby.RubyWorker$.create(RubyWorker.scala:51)
	at org.apache.spark.api.ruby.RubyRDD.compute(RubyRDD.scala:50)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ondra-m** [comment]
1) What ruby do you have?

2) Try reinstall **nio4r**.

3) Try `irb -rnio`.

**Comment by schlende** [comment]
ruby - 2.2.2p95
nio4r - 1.1.0

Everything seems to be installed correctly

**Comment by ondra-m** [comment]
1) Try:
- remove nio4r
- (re)install latest version

2) How you start ruby-spark + what did you do?
