### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by gnilrets** [ondra-m/ruby-spark#7]
Hi, I cloned this project, ran `bundle install` using Ruby 2.1.3 on OS X and then tried running the tests via `rspec spec`.  But I got the following error.  Am I missing an installation step?

````
/Users/gnilrets/git/ruby-spark/lib/spark.rb:177:in `require': cannot load such file -- ruby_spark_ext (LoadError)
        from /Users/gnilrets/git/ruby-spark/lib/spark.rb:177:in `<top (required)>'
        from /Users/gnilrets/git/ruby-spark/lib/ruby-spark.rb:1:in `require_relative'
        from /Users/gnilrets/git/ruby-spark/lib/ruby-spark.rb:1:in `<top (required)>'
        from /Users/gnilrets/git/ruby-spark/spec/spec_helper.rb:5:in `require'
        from /Users/gnilrets/git/ruby-spark/spec/spec_helper.rb:5:in `<top (required)>'
        from /Users/gnilrets/git/ruby-spark/spec/lib/collect_spec.rb:1:in `require'
        from /Users/gnilrets/git/ruby-spark/spec/lib/collect_spec.rb:1:in `<top (required)>'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
        from /Users/gnilrets/git/ruby-spark/vendor/bin/rspec:23:in `load'
        from /Users/gnilrets/git/ruby-spark/vendor/bin/rspec:23:in `<main>'
````

**Comment by ondra-m** [comment]
You have to build gem extensions by `rake compile`.

**Comment by gnilrets** [comment]
Ah thanks.  I tried that but I had forgotten to `rbenv rehash` before.  The compile was successful, but now I'm getting a new error when running `rspec spec`

````
[- ruby-spark -] rspec spec
/Users/gnilrets/git/ruby-spark/lib/spark/java_bridge/rjb.rb:18:in `import': org/apache/spark/SparkConf (NoClassDefFoundError)
        from /Users/gnilrets/git/ruby-spark/lib/spark/java_bridge/rjb.rb:18:in `block in import'
        from /Users/gnilrets/git/ruby-spark/lib/spark/java_bridge/rjb.rb:34:in `silence_warnings'
        from /Users/gnilrets/git/ruby-spark/lib/spark/java_bridge/rjb.rb:18:in `import'
        from /Users/gnilrets/git/ruby-spark/lib/spark/java_bridge/base.rb:53:in `block in load'
        from /Users/gnilrets/git/ruby-spark/lib/spark/java_bridge/base.rb:52:in `each'
        from /Users/gnilrets/git/ruby-spark/lib/spark/java_bridge/base.rb:52:in `load'
        from /Users/gnilrets/git/ruby-spark/lib/spark.rb:159:in `load_lib'
        from /Users/gnilrets/git/ruby-spark/spec/spec_helper.rb:9:in `<top (required)>'
        from /Users/gnilrets/git/ruby-spark/spec/lib/collect_spec.rb:1:in `require'
        from /Users/gnilrets/git/ruby-spark/spec/lib/collect_spec.rb:1:in `<top (required)>'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
        from /Users/gnilrets/git/ruby-spark/vendor/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
        from /Users/gnilrets/git/ruby-spark/vendor/bin/rspec:23:in `load'
        from /Users/gnilrets/git/ruby-spark/vendor/bin/rspec:23:in `<main>'
````

**Comment by ondra-m** [comment]
Please read https://github.com/ondra-m/ruby-spark/blob/master/README.md

You must compile Apache Spark.

```bash
git clone ...
rake compile
bin/ruby-spark build
rake
```

**Comment by gnilrets** [comment]
Perfect.  I didn't realize I'd have to re-do `ruby-spark build` after getting `rake compile` to work.

Thanks!
